# Use a Node.js base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock first for efficient caching
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Install TypeScript and ts-node globally
RUN yarn global add typescript ts-node

# Copy the entire project files
COPY . .
# Ensure .env is copied
COPY .env .env  

# Command to run the Kafka service
CMD ["ts-node", "./src/message-broker/index.ts"]
